import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UsersEditPopup from "./component/context/UsersEditPopup";
import LoginProvider from "./component/context/Login";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <LoginProvider>
          <UsersEditPopup>
            <div className="links">
              <Link href={"/"}>HOME</Link>
              <Link href={"/users"}>USERS</Link>
            </div>
            {children}
          </UsersEditPopup>
        </LoginProvider>
      </body>
    </html>
  );
}
